### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by theanmolsharma** [BitByte-TPC/Aperta-Fons#11]
### Checklist

- [x] Landing section of Home page
- [x] About section of Home page
- [x] Login and SignUp UI
- [x] Login and SignUp functionality
- [x] FAQs section of Home page
- [x] Prizes section of Home page
- [x] Footer
- [x] Navigation Bar
- [x] Dashboard (Contribution Page)
- [x] Form to submit contributions 
- [x] Responsiveness of website
